version: '3.3'

services:

    freefolk-youtube:
        image: cloud.canister.io:5000/seirius/freefolk-youtube:latest
        environment:
            PORT: ${YOUTUBE_PORT}
            YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
            LOGGER_LEVEL: ${LOGGER_LEVEL}
            MQTT_HOST: ${MQTT_HOST}
        restart: always
        ports:
            - ${YOUTUBE_PORT}:${YOUTUBE_PORT}
        labels:
            - com.centurylinklabs.watchtower.enable=true

    freefolk-filemanager:
        image: cloud.canister.io:5000/seirius/freefolk-filemanager:latest
        environment: 
            PORT: ${FILEMANAGER_PORT}
            REDIS_HOST: ${REDIS_HOST}
            FILE_EXPIRATION_TIME: ${FILEMANAGER_EXPIRATION_TIME}
            MQTT_HOST: ${MQTT_HOST}
        ports:
            - ${FILEMANAGER_PORT}:${FILEMANAGER_PORT}
        labels:
            - com.centurylinklabs.watchtower.enable=true

    freefolk-converter:
        image: cloud.canister.io:5000/seirius/freefolk-converter:latest
        environment: 
            FILE_MANAGER_HOST: ${FILEMANAGER_INTERNAL_HOST}
            PORT: ${CONVERTER_PORT}
            MQTT_HOST: ${MQTT_HOST}
        ports:
            - ${CONVERTER_PORT}:${CONVERTER_PORT}

    freefolk-queue:
        image: cloud.canister.io:5000/seirius/freefolk-queue:latest
        environment: 
            PORT: ${QUEUE_PORT}
            REDIS_HOST: ${REDIS_HOST}
        ports:
            - ${QUEUE_PORT}:${QUEUE_PORT}

    freefolk-download:
        image: cloud.canister.io:5000/seirius/freefolk-download:latest
        environment: 
            PORT: ${DOWNLOAD_PORT}
            YOUTUBE_ENDPOINT_HOST: ${YOUTUBE_INTERNAL_HOST}
            FILE_MANAGER_HOST: ${FILEMANAGER_INTERNAL_HOST}
            CONVERTER_HOST: ${CONVERTER_INTERNAL_HOST}
            QUEUE_HOST: ${QUEUE_INTERNAL_HOST}
            MQTT_HOST: ${MQTT_HOST}
        ports:
            - ${DOWNLOAD_PORT}:${DOWNLOAD_PORT}

    freefolk-web:
        image: cloud.canister.io:5000/seirius/freefolk-web:latest
        ports:
            - ${WEB_PORT}:${WEB_PORT}
            - ${WEB_SOCKET_PORT}:${WEB_SOCKET_PORT}
        environment: 
            PORT: ${WEB_PORT}
            MQTT_HOST: ${MQTT_HOST}
            LOGGER_LEVEL: ${LOGGER_LEVEL}
            REDIS_HOST: ${REDIS_HOST}

    freefolk-renderer:
        image: cloud.canister.io:5000/seirius/freefolk-renderer:latest
        ports:
            - ${RENDERER_PORT}:${RENDERER_PORT}

    redis:
        image: redis
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}

    mqtt:
        image: eclipse-mosquitto
        ports:
            - ${MQTT_PORT}:${MQTT_PORT}
            - ${MQTT_PORT_W}:${MQTT_PORT_W}

    nginx:
        image: nginx
        ports:
            - ${NGINX_PORT}:${NGINX_PORT}
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d

    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${DOCKER_CONFIG_PATH}:/config.json
        command: --interval 10 --cleanup --label-enable