version: '3.3'
services:

    freefolk-youtube:
        build: ./../freefolk-youtube
        environment:
            PORT: 3000
            YOUTUBE_API_KEY: AIzaSyDt_dCzvULBfqX9k2r-9-XJ2nRiEEHhUqg
        ports:
            - 3000:3000
        # volumes:
        #     - /home/andriy/dev/freefolk/freefolk-youtube:/usr/src/app
        # entrypoint: "npm run start:dev"

    freefolk-filemanager:
        build: ./../freefolk-filemanager
        environment: 
            PORT: 3001
            REDIS_HOST: redis
            FILE_EXPIRATION_TIME: 30
            MQTT_HOST: mqtt://mqtt
        volumes:
            - /home/andriy/Downloads/files:/usr/src/app/files
            # - /home/andriy/dev/freefolk/freefolk-filemanager:/usr/src/app
        ports:
            - 3001:3001
        # entrypoint: "npm run start:dev"

    freefolk-converter:
        build: ./../freefolk-converter
        environment: 
            FILE_MANAGER_HOST: http://freefolk-filemanager:3001
            PORT: 3002
            MQTT_HOST: mqtt://mqtt
        ports:
            - 3002:3002
        # volumes:
        #     - /home/andriy/dev/freefolk/freefolk-converter:/usr/src/app
        # entrypoint: "npm run start:dev"

    freefolk-queue:
        build: ./../freefolk-queue
        environment: 
            PORT: 3003
            REDIS_HOST: redis
        ports:
            - 3003:3003

    freefolk-download:
        build: ./../freefolk-download
        environment: 
            PORT: 3004
            YOUTUBE_ENDPOINT_HOST: http://freefolk-youtube:3000
            FILE_MANAGER_HOST: http://freefolk-filemanager:3001
            CONVERTER_HOST: http://freefolk-converter:3002
            QUEUE_HOST: http://freefolk-queue:3003
            MQTT_HOST: mqtt://mqtt
        ports:
            - 3004:3004
        # volumes:
        #     - /home/andriy/dev/freefolk/freefolk-download:/usr/src/app
        # entrypoint: "npm run start:dev"

    freefolk-web:
        build: ./../freefolk-web
        ports:
            - 3005:3005
            - 5000:5000
        # volumes:
        #     - /home/andriy/dev/freefolk/freefolk-web:/usr/src/app
        # entrypoint: "npm run start:dev"
        environment: 
            PORT: 3005
            MQTT_HOST: mqtt://mqtt

    redis:
        image: redis
        ports:
            - 6379:6379

    mqtt:
        image: eclipse-mosquitto
        ports:
            - 1883:1883
            - 9001:9001
      
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - /home/andriy/dev/freefolk/freefolk-renderer/dist:/var/www/freefolk.media
