version: '3.3'
services:

    freefolk-youtube:
        build: ./freefolk-youtube
        environment:
            PORT: ${YOUTUBE_PORT}
            YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
            LOGGER_LEVEL: ${LOGGER_LEVEL}
            MQTT_HOST: ${MQTT_HOST}
        ports:
            - ${YOUTUBE_PORT}:${YOUTUBE_PORT}
        # volumes:
        #     - /Users/waavistudio/dev/freefolk/freefolk-youtube:/usr/src/app
        # entrypoint: "npm run start:dev"

    freefolk-filemanager:
        build: ./freefolk-filemanager
        environment: 
            PORT: ${FILEMANAGER_PORT}
            REDIS_HOST: ${REDIS_HOST}
            FILE_EXPIRATION_TIME: ${FILEMANAGER_EXPIRATION_TIME}
            MQTT_HOST: ${MQTT_HOST}
        volumes:
            - /home/andriy/Downloads/files:/usr/src/app/files
            # - /home/andriy/dev/freefolk/freefolk-filemanager:/usr/src/app
        ports:
            - ${FILEMANAGER_PORT}:${FILEMANAGER_PORT}
        # entrypoint: "npm run start:dev"

    freefolk-converter:
        build: ./freefolk-converter
        environment: 
            FILE_MANAGER_HOST: ${FILEMANAGER_INTERNAL_HOST}
            PORT: ${CONVERTER_PORT}
            MQTT_HOST: ${MQTT_HOST}
        ports:
            - ${CONVERTER_PORT}:${CONVERTER_PORT}
        # volumes:
        #     - /home/andriy/dev/freefolk/freefolk-converter:/usr/src/app
        # entrypoint: "npm run start:dev"

    freefolk-queue:
        build: ./freefolk-queue
        environment: 
            PORT: ${QUEUE_PORT}
            REDIS_HOST: ${REDIS_HOST}
        ports:
            - ${QUEUE_PORT}:${QUEUE_PORT}

    freefolk-download:
        build: ./freefolk-download
        environment: 
            PORT: ${DOWNLOAD_PORT}
            YOUTUBE_ENDPOINT_HOST: ${YOUTUBE_INTERNAL_HOST}
            FILE_MANAGER_HOST: ${FILEMANAGER_INTERNAL_HOST}
            CONVERTER_HOST: ${CONVERTER_INTERNAL_HOST}
            QUEUE_HOST: ${QUEUE_INTERNAL_HOST}
            MQTT_HOST: ${MQTT_HOST}
        ports:
            - ${DOWNLOAD_PORT}:${DOWNLOAD_PORT}
        # volumes:
        #     - /home/andriy/dev/freefolk/freefolk-download:/usr/src/app
        # entrypoint: "npm run start:dev"

        
    freefolk-web:
        build: ./freefolk-web
        ports:
            - ${WEB_PORT}:${WEB_PORT}
            - ${WEB_SOCKET_PORT}:${WEB_SOCKET_PORT}
        # volumes:
        #     - /home/andriy/dev/freefolk/freefolk-web:/usr/src/app
        # entrypoint: "npm run start:dev"
        environment: 
            PORT: ${WEB_PORT}
            MQTT_HOST: ${MQTT_HOST}
            LOGGER_LEVEL: ${LOGGER_LEVEL}
                        
    # freefolk-bot:
    #     build: ./freefolk-bot
    #     environment:
    #         PORT: ${BOT_PORT}
    #         BOT_KEY: ${BOT_KEY}
    #         MQTT_HOST: ${MQTT_HOST}
    #         YOUTUBE_HOST: ${YOUTUBE_INTERNAL_HOST}
    #         DOWNLOAD_HOST: ${DOWNLOAD_INTERNAL_HOST}
    #         FILEMANAGER_HOST: ${FILEMANAGER_INTERNAL_HOST}
    #         FILEMANAGER_PUBLIC_HOST: ${FILEMANAGER_PUBLIC_HOST}
        # volumes:
        #     - /home/andriy/dev/freefolk/freefolk-bot:/usr/src/app
        # entrypoint: "npm run start:dev"
        # ports:
        #     - ${BOT_PORT}:${BOT_PORT}

    freefolk-renderer:
        build: ./freefolk-renderer
        ports:
            - ${RENDERER_PORT}:${RENDERER_PORT}
        # volumes:
        #     - ./freefolk-renderer/nginx/conf.d:/etc/nginx/conf.d
        #     - ./freefolk-renderer/dist:/var/www/freefolk.media

    redis:
        image: redis
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}

    mqtt:
        image: eclipse-mosquitto
        ports:
            - ${MQTT_PORT}:${MQTT_PORT}
            - ${MQTT_PORT_W}:${MQTT_PORT_W}

    nginx:
        image: nginx
        ports:
            - ${NGINX_PORT}:${NGINX_PORT}
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            # - /home/andriy/dev/freefolk/freefolk-renderer/dist:/var/www/freefolk.media
